CREATE TABLE topicos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    mensagem TEXT NOT NULL,
    autor VARCHAR(255) NOT NULL,
    categoria ENUM('PROGRAMACAO', 'IA', 'FRONTEND', 'DADOS', 'INOVACAO', 'MARKETING', 'DESIGN') NOT NULL,
    data_criacao TIMESTAMP NOT NULL,
    status ENUM('NAO_RESPONDIDO', 'RESPONDIDO', 'RESOLVIDO') NOT NULL,
    aberto BOOLEAN NOT NULL,
    quantidade_respostas INT NOT NULL,
    curso_id BIGINT,
    CONSTRAINT fk_curso FOREIGN KEY (curso_id) REFERENCES cursos(id) ON DELETE SET NULL
);